"C:x/consumer":
- changed-files:
  - any-glob-to-any-file: x/ccv/consumer/**
"C:x/democracy":
- changed-files:
  - any-glob-to-any-file: x/ccv/democracy/**
"C:x/provider":
- changed-files:
  - any-glob-to-any-file: x/ccv/provider/**
"C:x/types":
- changed-files:
  - any-glob-to-any-file: x/ccv/types/**
"C:Docs":
- changed-files:
  - any-glob-to-any-file: docs/docs/**
"C:ADR":
- changed-files:
  - any-glob-to-any-file: docs/docs/adrs/**
"C:CI":
- changed-files:
  - any-glob-to-any-file: .github/**/*.yml
  - any-glob-to-any-file: buf.work.yaml
  - any-glob-to-any-file: .mergify.yml
  - any-glob-to-any-file: .golangci.yml
  - any-glob-to-any-file: mlc_config.json
  - any-glob-to-any-file: sonar-project.properties
"C:Build":
- changed-files:
  - any-glob-to-any-file: Makefile
  - any-glob-to-any-file: Dockerfile
  - any-glob-to-any-file: scripts/**
"C:Testing":
- changed-files:
  - any-glob-to-any-file: app/**
  - any-glob-to-any-file: cmd/**
  - any-glob-to-any-file: tests/**
  - any-glob-to-any-file: testutil/**