language: "en"
early_access: false
reviews:
    request_changes_workflow: false
    high_level_summary: true
    poem: false
    review_status: false
    collapse_walkthrough: true
    path_filters:
        - "!api/"
        - "!docs/"
    path_instructions:
        - path: "**/*.go"
          instructions: "Review the Golang code for conformity with the Uber Golang style guide, highlighting any deviations."
        - path: "tests/e2e/*"
          instructions: |
              "Assess the e2e test code assessing sufficient code coverage for the changes associated in the pull request"
        - path: "tests/integration/*"
          instructions: |
              "Assess the e2e test code assessing sufficient code coverage for the changes associated in the pull request"
        - path: "**/*_test.go"
          instructions: |
              "Assess the unit test code assessing sufficient code coverage for the changes associated in the pull request"
        - path: "**/*.md"
          instructions: |
              "Assess the documentation for misspellings, grammatical errors, missing documentation and correctness. Please DO NOT report any missing or superfluous newlines, in particular at the end or beginning of files."
        - path: ".changelog/*"
          instructions: |
              "Assess the changes in the changelog for correctness and completeness, particularly flagging missing changes"
    auto_review:
        enabled: true
        ignore_title_keywords:
            - "WIP"
            - "DO NOT MERGE"
        drafts: false
        base_branches:
            - "main"
            - "feat/*"
            - "release/*"
chat:
    auto_reply: true
