run:
  tests: true
  timeout: 10m
  sort-results: true
  allow-parallel-runners: true
  exclude-dir: testutil/testdata

linters:
  disable-all: true
  enable:
    - depguard
    - dogsled
    - exportloopref
    - goconst
    - gocritic
    - gofumpt
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - staticcheck
    - revive
    - stylecheck
    - typecheck
    - thelper
    - unconvert
    - unused

issues:
  gofumpt:
    # Module path which contains the source code being formatted.
    # Default: ""
    module-path: github.com/cosmos/interchain-security
    # Choose whether to use the extra rules.
    # Default: false
    extra-rules: true
  exclude-rules:
    - text: "Use of weak random number generator"
      linters:
        - gosec
    - text: "ST1003:"
      linters:
        - stylecheck
    # FIXME: Disabled until golangci-lint updates stylecheck with this fix:
    # https://github.com/dominikh/go-tools/issues/389
    - text: "ST1016:"
      linters:
        - stylecheck
    - path: "migrations"
      text: "SA1019:"
      linters:
        - staticcheck
    - text: "leading space"
      linters:
        - nolintlint

  max-issues-per-linter: 10000
  max-same-issues: 10000

linters-settings:
  gocritic:
    disabled-checks:
      - appendAssign
      - ifElseChain
  dogsled:
    max-blank-identifiers: 3
  revive:
    rules:
      - name: var-naming
        disabled: true
  maligned:
    # print struct with more effective memory layout or not, false by default
    suggest-new: true
  nolintlint:
    allow-unused: false
    allow-leading-space: true
    require-explanation: false
    require-specific: false
