defaults:
  actions:
    backport:
      assignees:
        - "{{ author }}"

queue_rules:
  - name: default
    conditions:
      - "#approved-reviews-by>1"

pull_request_rules:
  - name: Backport patches to the release/v4.3.x branch
    conditions:
      - base=main
      - label=A:backport/v4.3.x
    actions:
      backport:
        branches:
          - release/v4.3.x
  - name: Backport patches to the release/v4.3.x-lsm branch
    conditions:
      - base=main
      - label=A:backport/v4.3.x-lsm
    actions:
      backport:
        branches:
          - release/v4.3.x-lsm
  - name: Backport patches to the release/v4.4.x branch
    conditions:
      - base=main
      - label=A:backport/v4.4.x
    actions:
      backport:
        branches:
          - release/v4.4.x
  - name: Backport patches to the release/v5.x branch
    conditions:
      - base=main
      - label=A:backport/v5.x
    actions:
      backport:
        branches:
          - release/v5.x
  - name: Backport patches to the release/v5.2.x branch
    conditions:
      - base=main
      - label=A:backport/v5.2.x
    actions:
      backport:
        branches:
          - release/v5.2.x
  - name: Backport patches to the release/v6.0.x branch
    conditions:
      - base=main
      - label=A:backport/v6.0.x
    actions:
      backport:
        branches:
          - release/v6.0.x
