defaults:
  actions:
    backport:
      assignees:
        - "{{ author }}"

queue_rules:
  - name: default
    conditions:
      - "#approved-reviews-by>1"

pull_request_rules:
  - name: Backport patches to the release/v2.0.x branch
    conditions:
      - base=main
      - label=A:backport/v2.0.x
    actions:
      backport:
        branches:
          - release/v2.0.x
  - name: Backport patches to the release/v3.0.x branch
    conditions:
      - base=main
      - label=A:backport/v3.0.x
    actions:
      backport:
        branches:
          - release/v3.0.x
  - name: Backport patches to the release/v3.1.x branch
    conditions:
      - base=main
      - label=A:backport/v3.1.x
    actions:
      backport:
        branches:
          - release/v3.1.x
  - name: Backport patches to the release/v4.0.x branch
    conditions:
      - base=main
      - label=A:backport/v4.0.x
    actions:
      backport:
        branches:
          - release/v4.0.x
