# syntax=docker/dockerfile:1

# Consumer image to be used for compatibility tests with provider
# use docker's build argument --build-arg to overwrite the defaults
# e.g. docker build --build-arg CONSUMER_TAG=v3.1.0
ARG CONSUMER_VERSION
ARG CONSUMER_IMAGE="cosmos-ics"


FROM golang:1.20-alpine AS is-builder

ENV PACKAGES curl make git libc-dev bash gcc linux-headers
RUN apk add --no-cache $PACKAGES

ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOFLAGS="-buildvcs=false"

# cache go modules - done before the files are copied to allow docker to better cache
COPY go.mod /go.mod
COPY go.sum /go.sum
RUN go mod download


# Copy in the repo under test
ADD . /ics-consumer

WORKDIR /ics-consumer

# Do not specify version here. It leads to odd replacement behavior
RUN if [ -d "./cosmos-sdk" ]; then go mod edit -replace github.com/cosmos/cosmos-sdk=./cosmos-sdk; fi
RUN go mod tidy

# Install interchain security binary
RUN make install


# The image from where the consumer implementation will be used
# Defaults to
FROM --platform=linux/amd64 ${CONSUMER_IMAGE}:${CONSUMER_VERSION} AS consumer

# Get Hermes build
# FROM ghcr.io/informalsystems/hermes:v1.4.0 AS hermes-builder
FROM ghcr.io/informalsystems/hermes:v1.7.2@sha256:e6a81a0ca0b335f0b498bf74cc5c6a083ec58b2b32c38d142f70d6610bd6a6f7 AS hermes-builder
# FROM otacrew/hermes-ics:evidence-cmd AS hermes-builder

# Get CometMock
FROM ghcr.io/informalsystems/cometmock:v0.37.x as cometmock-builder

# Get GoRelay   er
FROM ghcr.io/informalsystems/relayer-no-gas-sim:v2.3.0-rc4-no-gas-sim AS gorelayer-builder

FROM --platform=linux/amd64 fedora:39
RUN dnf update -y
RUN dnf install -y which iproute iputils procps-ng vim-minimal tmux net-tools htop jq
USER root
ARG CONSUMER_VERSION

COPY --from=hermes-builder /usr/bin/hermes /usr/local/bin/
COPY --from=cometmock-builder /usr/local/bin/cometmock /usr/local/bin/cometmock
COPY --from=gorelayer-builder /bin/rly /usr/local/bin/

# Copy consumer from specified image
COPY --from=consumer /usr/local/bin/interchain-security-cd /usr/local/bin/interchain-security-cd
COPY --from=consumer /usr/local/bin/interchain-security-cdd /usr/local/bin/interchain-security-cdd
COPY --from=consumer /usr/local/bin/interchain-security-sd /usr/local/bin/interchain-security-sd
COPY --from=consumer /testnet-scripts /consumer-${CONSUMER_VERSION}/testnet-scripts

# Copy provider from local build
COPY --from=is-builder /go/bin/interchain-security-pd /usr/local/bin/interchain-security-pd

# Copy in the shell scripts that run the testnet
ADD ./tests/e2e/testnet-scripts /testnet-scripts

# Copy in the hermes config
ADD ./tests/e2e/testnet-scripts/hermes-config.toml /root/.hermes/config.toml
