package types

// Provider events
const (
	EventTypeConsumerClientCreated     = "consumer_client_created"
	EventTypeAssignConsumerKey         = "assign_consumer_key"
	EventTypeChangeConsumerRewardDenom = "change_consumer_reward_denom"
	EventTypeExecuteConsumerChainSlash = "execute_consumer_chain_slash"
	EventTypeSetConsumerCommissionRate = "set_consumer_commission_rate"
	EventTypeOptIn                     = "opt_in"
	EventTypeOptOut                    = "opt_out"
	EventTypeCreateConsumer            = "create_consumer"
	EventTypeUpdateConsumer            = "update_consumer"
	EventTypeRemoveConsumer            = "remove_consumer"
	EventTypeReceivedRewards           = "received_ics_rewards"
	EventTypeDistributedRewards        = "distributed_ics_rewards"

	AttributeInfractionHeight          = "infraction_height"
	AttributeInitialHeight             = "initial_height"
	AttributeTrustingPeriod            = "trusting_period"
	AttributeUnbondingPeriod           = "unbonding_period"
	AttributeValsetHash                = "valset_hash"
	AttributeProviderValidatorAddress  = "provider_validator_address"
	AttributeConsumerConsensusPubKey   = "consumer_consensus_pub_key"
	AttributeAddConsumerRewardDenom    = "add_consumer_reward_denom"
	AttributeRemoveConsumerRewardDenom = "remove_consumer_reward_denom"
	AttributeSubmitterAddress          = "submitter_address"
	AttributeConsumerCommissionRate    = "consumer_commission_rate"
	AttributeConsumerId                = "consumer_id"
	AttributeConsumerChainId           = "consumer_chain_id"
	AttributeConsumerName              = "consumer_name"
	AttributeConsumerOwner             = "consumer_owner"
	AttributeConsumerSpawnTime         = "consumer_spawn_time"
	AttributeConsumerPhase             = "consumer_phase"
	AttributeConsumerTopN              = "consumer_topn"
	AttributeRewardDenom               = "reward_denom"
	AttributeRewardAmount              = "reward_amount"
	AttributeRewardDistribution        = "reward_distribution"
	AttributeRewardTotal               = "total_rewards"
	AttributeRewardDistributed         = "distributed_rewards"
	AttributeRewardCommunityPool       = "community_pool_rewards"
)
