name: E2E HappyPath Tests
on:
  push:
    branches:
      - main
      - release/v*
      - feat/*
  pull_request:
    branches:
      - main
      - release/v*
      - feat/*
jobs:
  e2e-happy-path:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20" # The Go version to download (if necessary) and use.
      - name: Proto Check
        run: make proto-check
      - name: E2E tests
        run: make test-e2e-short