name: E2E HappyPath Tests
on:
  push:
    branches:
      - main
      - release/v*
      - feat/*
  pull_request:
    branches:
      - main
      - release/v*
      - feat/*
jobs:
  E2E_Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - name: E2E tests
        run: make test-e2e-short
  Cometmock_Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - name: E2E tests
        run: make test-e2e-short-cometmock
