name: Test
on:
  workflow_call:
  pull_request:
  merge_group:
  push:
    branches:
      - main
      - release/v*
      - feat/*

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}-tests
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          check-latest: true
          cache: true
          cache-dependency-path: go.sum
      - uses: technote-space/get-diff-action@v6.1.2
        id: git_diff
        with:
          PATTERNS: |
            **/*.proto
            **/*.go
            go.mod
            go.sum
            **/go.mod
            **/go.sum
            **/Makefile
            Makefile
      - uses: actions/cache@v4.0.2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.mod') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: proto check
        run: make proto-check
      - name: test & coverage report creation
        if: env.GIT_DIFF
        run: |
          make test-unit-cov
      # - uses: actions/upload-artifact@v4
      #   if: env.GIT_DIFF
      #   with:
      #     name: "${{ github.sha }}-coverage"
      #     path: ./profile.out

  test-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          check-latest: true
          cache: true
          cache-dependency-path: go.sum
      - uses: technote-space/get-diff-action@v6.1.2
        id: git_diff
        with:
          PATTERNS: |
            **/*.go
            go.mod
            go.sum
            **/go.mod
            **/go.sum
            **/Makefile
            Makefile
      - name: integration tests
        if: env.GIT_DIFF
        run: |
          make test-integration-cov
      # - uses: actions/upload-artifact@v4
      #   if: env.GIT_DIFF
      #   with:
      #     name: "${{ github.sha }}-integration-coverage"
      #     path: ./integration-profile.out

  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: checkout LFS objects
        run: git lfs checkout
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          check-latest: true
          cache: true
          cache-dependency-path: go.sum
      - uses: technote-space/get-diff-action@v6.1.2
        id: git_diff
        with:
          PATTERNS: |
            **/*.go
            go.mod
            go.sum
            **/go.mod
            **/go.sum
            **/Makefile
            Makefile
            Dockerfile*
      - name: e2e tests
        if: env.GIT_DIFF
        run: |
          make test-e2e-short

  model-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: checkout LFS objects
        run: git lfs checkout
      - uses: actions/setup-node@v4
        with:
          node-version: ">= 18"
          check-latest: true
      - run: npm i @informalsystems/quint -g
      - uses: technote-space/get-diff-action@v6.1.2
        id: git_diff
        with:
          PATTERNS: |
            tests/mbt/model/**.qnt
      - name: verify the Quint model
        if: env.GIT_DIFF
        run: |
          make verify-models
